Update from upstream branch
MoveOnOrg/parsons pull request #21
Opened 2022-09-16 19:31 UTC by crayolakat

2022-09-22 15:48 UTC, sjwmoveon requested changes
Sorry, this is absolutely my fault - but I can't approve this until https://github.com/move-coop/parsons/pull/745 is merged as otherwise it will break fundraising-parsons-scripts.

2022-09-22 17:50 UTC, sjwmoveon commented
The pull request I mentioned has been merged - can you add that change as well?

2022-09-27 18:38 UTC, crayolakat commented
@sjwmoveon Done!

2022-09-27 20:01 UTC, sjwmoveon approved these changes

2022-09-27 20:22 UTC, merged